version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3005:3005
    environment:
      - PORT=3005
      - DB_HOST=psql
    volumes:
      - ./:/app

  psql:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - psql:/var/lib/postgresql/data

volumes:
  psql:
