version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3005:3005
    volumes:
      - ./:/app
    command: tail -f /dev/null

  psql:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - psql:/var/lib/postgresql/data

volumes:
  psql:
    driver: local
