FROM ruby:2.7.6

ENV GEM_HOME="/usr/local/bundle"
ENV PATH $GEM_HOME/bin:$GEM_HOME/gems/bin:$PATH

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
      build-essential \
      libpq-dev

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get update && apt-get install -y nodejs

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

RUN gem install \
      bundler:2.3.17 \
      rake:13.0.6 \
      rails:6.1.6

RUN mkdir -p /app
WORKDIR /app

ADD Gemfile /app
ADD Gemfile.lock /app

RUN (bundle check || bundle install) && \
    cp Gemfile.lock /tmp

ENTRYPOINT ["/bin/bash", "/app/docker-entrypoint.sh"]

CMD (rm tmp/pids/server.pid ||:) && \
    (mkdir -p tmp/pids) && \
    bundle exec rails s -b 0.0.0.0
