FROM ruby:2.7.6

ENV BUNDLE_PATH=/app/.bundle

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
      build-essential \
      libpq-dev \
      nodejs

RUN gem install \
      bundler:2.3.17 \
      rake:13.0.6 \
      rails:6.1.6

RUN mkdir /app

WORKDIR /app
